### ISSUE TITLE
Quick Sort Algorithm

### ISSUE THREAD

**Issue by Scholasticpal** [Scholasticpal/HacktoberFest2021_#2]
add quick sort algorithm under any language.

**Comment by sohamp19** [comment]
Hey @Scholasticpal , I'd like to implement Quicksort in java.
This will be my first contribution.

**Comment by shrutinisal** [comment]
Hey @Scholasticpal  I can implement it in C++ . I'd like to make a contribution. Can you assign this issue to me?

**Comment by Scholasticpal** [comment]
@sohamp19 yes it's working, I have merged your PR :)

**Comment by soumyo2002** [comment]
Hey @Scholasticpal can I work on this issue?

**Comment by jhaakshita27** [comment]
Hey @Scholasticpal. Can I making a pr request please for quick sort algorithm? Please. 
C++/java would be preferable. Thank u
