### ISSUE TITLE
Add Basic Calculator

### ISSUE THREAD

**Issue by Scholasticpal** [Scholasticpal/HacktoberFest2021_#34]
This issue is for beginners, interested to contribute to hacktoberfest!🚀

Add projects under Language/Calculator/ for example a Calculator implemented in C++ will go under the folder C++/Calculator/  

(Note: Only files added in the mentioned way will be merged)⚠

**Comment by LucasRobs** [comment]
so in this problem i would have to implement a calculator in c++?
