### ISSUE TITLE
Tic Tac Toe

### ISSUE THREAD

**Issue by Scholasticpal** [Scholasticpal/HacktoberFest2021_#47]
This issue is for beginners, interested to contribute to hacktoberfest!🚀

Add projects under Language/TicTacToe/ for example a Calculator implemented in C++ will go under the folder Java/TicTacToe/

(Note: Only files added in the mentioned way will be merged)⚠

**Comment by Axe-Pearl** [comment]
Hey @Scholasticpal , Please check my PR ?
